### ISSUE TITLE
Crash on ubuntu

### ISSUE THREAD

**Issue by danielgomezrico** [bitrise-steplib/bitrise-step-flutter-installer#19]
### Troubleshooting

- Which version of the step is effected? _1.2.3_
- Is the issue reproducible with the latest version? _YES _
- Does the issue happen sporadically, or every time? _ EVERY TIME_

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

When the step runs on a linux/ubuntu 16.04 machine it fails with an error, 
Im using a bundle url: https://storage.googleapis.com/flutter_infra/releases/stable/macos/flutter_macos_1.22.4-stable.zip

### Bitrise info

- Build URL: https://app.bitrise.io/build/84d0e74e884f1d4d#?tab=log
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: _NO_

```
Downloading Flutter SDK
Cleaning SDK target path: /root/flutter-sdk
Downloading and unarchiving Flutter from installation bundle: https://storage.googleapis.com/flutter_infra/releases/stable/macos/flutter_macos_1.22.4-stable.zip
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now
failed to download and unarchive bundle, error: tar command failed: exit status 2, out: xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

### Steps to reproduce
1. Setup your ci machine to run on ubuntu
1. Add this step
1. Put the bundle url

**Comment by mateherber** [comment]
Hi @danielgomezrico ,

Thanks for reporting this issue. Can you please try with the linux bundle url: https://storage.googleapis.com/flutter_infra/releases/stable/linux/flutter_linux_1.22.4-stable.tar.xz

Please write back the result to this issue.

**Comment by danielgomezrico** [comment]
@mateherber it does work with that `tar.xz` link :)

**Comment by mateherber** [comment]
Awesome! I think this issue can be closed then.

**Comment by danielgomezrico** [comment]
I think that it will be good to add the link to the docs if it is not already there, thanks.
