### ISSUE TITLE
Flutter Version is not been installed or used

### ISSUE THREAD

**Issue by danielgomezrico** [bitrise-steplib/bitrise-step-flutter-installer#27]
### Troubleshooting

- [ ] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 1.11.5
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

I have this setup:
![image](https://user-images.githubusercontent.com/76348/151546566-5627edd7-e089-455f-8bb0-71d1990e4ac3.png)

And after I made a build with SSH  and run `flutter doctor -v` it says that the version that is instealled is `1.26.0-17.8.pre`, why? it should be the one that I wanted to install which is `2.8.1`

### Bitrise info

- Build URL: https://app.bitrise.io/build/06c395dc-e400-4638-9fb5-4a7cd057069b
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: _NO_

<details>
  <pre>
[✓] Flutter (Channel beta, 1.26.0-17.8.pre, on Mac OS X 10.15.7 19H15 darwin-x64, locale en)
    • Flutter version 1.26.0-17.8.pre at /Users/vagrant/fvm/versions/1.26.0-17.8.pre
    • Framework revision 044f2cf560 (11 months ago), 2021-02-24 13:02:05 -0800
    • Engine revision 042c82b02c
    • Dart version 2.12.0 (build 2.12.0-259.16.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /usr/local/share/android-sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /usr/local/share/android-sdk
    • ANDROID_SDK_ROOT = /usr/local/share/android-sdk
    • Java binary at: /Users/vagrant/.jenv/versions/11/bin/java
    • Java version OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode-12.4.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.11.2

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
vm-osx-xcode-12:git vagrant$ flutter doctor -v
[✓] Flutter (Channel beta, 1.26.0-17.8.pre, on Mac OS X 10.15.7 19H15 darwin-x64, locale en)
    • Flutter version 1.26.0-17.8.pre at /Users/vagrant/fvm/versions/1.26.0-17.8.pre
    • Framework revision 044f2cf560 (11 months ago), 2021-02-24 13:02:05 -0800
    • Engine revision 042c82b02c
    • Dart version 2.12.0 (build 2.12.0-259.16.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /usr/local/share/android-sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /usr/local/share/android-sdk
    • ANDROID_SDK_ROOT = /usr/local/share/android-sdk
    • Java binary at: /Users/vagrant/.jenv/versions/11/bin/java
    • Java version OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode-12.4.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.11.2

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
  </pre>
</details>

### Steps to reproduce

Create a workflow like this: 

![image](https://user-images.githubusercontent.com/76348/151546871-a2d5973c-5666-4130-a2b5-c087ab090af3.png)

With this bundle url: https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_2.8.1-stable.zip
And run it with ssh, then run `flutter doctor -v` inside of your project code `cd git/ && flutter doctor -v`

**Comment by ofalvai** [comment]
@danielgomezrico if you still face this issue, please also check the output of the Flutter Installer step. Using Flutter commands through SSH might execute a different binary than what the step exposes to the rest of the workflow
