### ISSUE TITLE
FVM conflicts with installed flutter via url

### ISSUE THREAD

**Issue by danielgomezrico** [bitrise-steplib/bitrise-step-flutter-installer#30]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 0.11.6
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? NO

### My Setup:
Step Version: `0.11.6`
![image](https://user-images.githubusercontent.com/76348/178039623-b0b0e67d-3354-4050-99fe-68d5f3d73db5.png)

### Issue description
The flutter version defined in the action is not being used:

### Bitrise info

- Build URL: [_Please share the build URL with us._](https://app.bitrise.io/build/e22c2c3c-ec80-4102-8425-e3f79c3503ce)
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: _YES_
- Log: 
I went and run the build with ssh getting:

flutter doctor:
```console
'vm-osx-xcode-13:git vagrant$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.3, on macOS 11.5.1 20G80 darwin-x64, locale en)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google
    Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[!] Android Studio (not installed)
[!] Connected device
    ! No devices available
[✓] HTTP Host Availability

! Doctor found issues in 4 categories.
```

> As you can see it says  2.10.3 but it should be 3.0.4

Image from build:
![image](https://user-images.githubusercontent.com/76348/178039769-402232cb-754a-4bbd-8d5f-aa1696d75f17.png)

I found this because the job ends up been aborted after 1 hour, and checking the same job in ssh with `flutter test` I got:

```console
../flutter-sdk/flutter/packages/flutter_test/lib/src/finders.dart:766:26: Error: This requires the
'super-parameters' language feature to be enabled.
Try updating your pubspec.yaml to set the minimum SDK constraint to 2.15 or higher, and running 'pub
get'.
  _KeyFinder(this.key, { super.skipOffstage });
```

Flutte `3.0.4` requires `2.17.5` and that is already defined in my pubspec.yml:
```yml
environment:
  sdk: 2.17.5
  flutter: 3.0.4
```

### Steps to reproduce
Define your step and setup like:
Url:  https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_3.0.4-stable.zip
![image](https://user-images.githubusercontent.com/76348/178039925-a9afcaea-3369-46f5-80cd-ef6a10f5bf1e.png)

# Hints
1. I dont understand why fvm says that there are multiple versions installed if I set just 1:
```console
vm-osx-xcode-13:~ vagrant$ fvm list
Cache Directory:  /Users/vagrant/fvm/versions

2.10.3 (global)
2.2.3
1.26.0-17.8.pre
1.22.6
```

2. I dont understand why flutter points to the old version and not he is one I defined in the URL (3.0.4):

3. I dont undestand why the setup uses RVM and setup the path in `.bashrc` to use RVM instead of using `/Users/vagrant/flutter-sdk/flutter` path, which is where this step installs flutter:
```
# Flutter & fvm
export PATH="$PATH:$HOME/.pub-cache/bin"
export PATH="$PATH:$HOME/fvm/default/bin"
```

5. I dont understand why the flutter binary points to the RVM binary that is using the old versions:
```console
vm-osx-xcode-13:~ vagrant$ which flutter
/Users/vagrant/fvm/default/bin/flutter
```

6. If I go and install the flutter version I have in the action setup by hand it just works fine:
```console
vm-osx-xcode-13:git vagrant$ fvm use 3.0.4
Flutter "3.0.4" is not installed.
Would you like to install it? Y/n: Y

Installing version: 3.0.4...

vm-osx-xcode-13:git vagrant$ fvm global

[1] 3.0.4
[2] 2.10.3
[3] 2.2.3
[4] 1.26.0-17.8.pre
[5] 1.22.6


vm-osx-xcode-13:git vagrant$ 1

vm-osx-xcode-13:git vagrant$ flutter test
Tests run fine
```

**Comment by tothszabi** [comment]
@danielgomezrico  Thank you for reporting this. I will forward some of your question to the Infra team because I do not have answer for them yet. 

The `flutter-installer` step can be used to override the local Flutter setup in the sense that it can download any version you specify. This means that at the end the step also overrides the `$PATH` env var and makes sure that any subsequent `flutter` command invocation points to the newly installed SDK. 

I have run this in an example project (with the same Flutter config as you have used) and all my logged `flutter` calls were pointing to the newly installed SDK. 

In your case it seems like when fastlane executes `flutter test` then the flutter executable points to the old one. We can easily double checks this. Could you insert a script step after the `flutter-installer` step and before the `fastlane` one with the following contents and post their output?

Script:
```
#!/usr/bin/env bash
set -e
set -o pipefail
set -x

which flutter

printenv | grep -e "^PATH"  
```

**Comment by danielgomezrico** [comment]
We do run Fastlane, but I tested using SSH and run the flutter scripts directly, we do not install or change the flutter SDK from Fastlane.

Please check the issue, I put what was the PATH, where it was, which version does it have installed and so on

**Comment by danielgomezrico** [comment]
After running that I got:

```console
+ which flutter
/Users/vagrant/flutter-sdk/bin/flutter
+ printenv
+ grep -e '^PATH'
PATH=/Users/vagrant/flutter-sdk/bin:/Users/vagrant/.bitrise/tools:/usr/local/opt/php@7.4/sbin:/usr/local/opt/php@7.4/bin:/Users/vagrant/.jenv/shims:/Users/vagrant/.rbenv/shims:/usr/local/bin:/usr/local/sbin:~/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/usr/local/sbin:~/bin:/usr/gnu/bin:.:/usr/local/go/bin:/go/bin:/.pub-cache/bin:/fvm/default/bin:/usr/sbin:/usr/local/go/bin:/Users/vagrant/go/bin:/Users/vagrant/.pub-cache/bin:/Users/vagrant/fvm/default/bin:/Users/vagrant/bitrise/tools/cmd-bridge/bin/osx:/usr/local/share/android-sdk/ndk-bundle:/usr/local/share/android-sdk/platform-tools:/usr/local/share/android-sdk/cmdline-tools/cmdline-tools/bin:/Users/vagrant/.jenv/bin
```

**Comment by danielgomezrico** [comment]
Is there any update here?
