### ISSUE TITLE
Flutter Install does not respect requested version

### ISSUE THREAD

**Issue by johnhess** [bitrise-steplib/bitrise-step-flutter-installer#31]
The step accepts a "version".  Here, I've selected 3.7.1, but 2.10.3 gets installed.

```
+------------------------------------------------------------------------------+

| (1) Flutter Install                                                          |
+------------------------------------------------------------------------------+
| id: flutter-installer                                                        |
| version: 0.11.6                                                              |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2023-03-20T20:54:57Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
 * [OK] Step dependency (git) installed, available.
 * [OK] Step dependency (tar) installed, available.
Config:
- Version: 3.7.1
- IsUpdate: false
- BundleURL: 
- IsDebug: false
Preinstalled Flutter binary path: /Users/vagrant/fvm/default/bin/flutter
$ flutter "--version"
╔════════════════════════════════════════════════════════════════════════════╗
║ A new version of Flutter is available!                                     ║
║                                                                            ║
║ To update to the latest version, run "flutter upgrade".                    ║
╚════════════════════════════════════════════════════════════════════════════╝
Flutter 2.10.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7e9793dee1 (1 year, 1 month ago) • 2022-03-02 11:23:12 -0600
Engine • revision bd539267b4
Tools • Dart 2.16.1 • DevTools 2.9.2
Preinstalled Flutter version: 2.10.3
Downloading Flutter SDK
```

### Troubleshooting

- [X] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 0.11.6 (via 0.x.x)
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? NOT APPLICABLE; I don't want to mess up my own flutter install.

### Notes

As a workaround, I am running `flutter upgrade`.

**Comment by godrei** [comment]
Hi @johnhess ,
based on the log chunk you shared, I'm not sure if there is an issue with the Step.
In these early lines, the Step just reports the preinstalled Flutter SDK version.
The last line is: `Downloading Flutter SDK`, the newly installed Flutter SDK version should be printed around the end of the step log box.

**Comment by johnhess** [comment]
Having some more experience with the step, you're right that log chunk is misleading.  I was having trouble getting the new version to be added to the `$PATH`.

I'd thought that selecting "stable" (or other releases) would upgrade the `flutter` command on the `$PATH`, but later figured out that I also need to flip the upgrade bit per this description.

> If the version selected is stable and a preinstalled Flutter version from the stable channel with version 1.2.1 exists:
> Setting to false will not update, even if a later release exists.
