### ISSUE TITLE
Expose dart binaries as well

### ISSUE THREAD

**Issue by guitcastro** [bitrise-steplib/bitrise-step-flutter-installer#5]
We use `dartftm` and `dartanalyzer` tools to check code style and do static analyser in our code. So I suggest to added the files under fluter-sdk/cache/dart-sdk/bin in the `$PATH`as well.

**Comment by daniel-v** [comment]
Quite old post but here it is anyway.

[Code](https://github.com/bitrise-steplib/bitrise-step-flutter-installer/blob/master/main.go#L148) shows that there are no Flutter specific env vars exposed. So what you can do in a Script workflow step.

```sh
export PATH=$PATH:$(dirname `which flutter`)
```

That is, it would work if you didn't have to use `envman` to "persist" env variable across steps. So what you can do instead is

```
envman add --key DART_SDK --value $(dirname `which flutter`)
```

**Comment by godrei** [comment]
Hi @guitcastro , sorry for the late response and thanks for the feature request. I opened a ticket to implement this feature.
