### ISSUE TITLE
Run Script of the IOS Runner fails

### ISSUE THREAD

**Issue by AlexandreRoba** [bitrise-steplib/bitrise-step-flutter-installer#6]
Dear all, I'm trying to setup a Flutter IOS build on Bitrise.
My build fails in the IOS archive step with the error:
```bash
▸ Check Dependencies
▸ Running script '[CP] Check Pods Manifest.lock'
▸ Running script 'Run Script'
Last lines of the Xcode's build log:
Compiler terminated unexpectedly.
Failed to build /Users/vagrant/git.
Command /bin/sh failed with exit code 255
** ARCHIVE FAILED **
The following build commands failed:
	PhaseScriptExecution Run\ Script /Users/vagrant/Library/Developer/Xcode/DerivedData/Runner-fvdlvfvunbwmbcgkbjykdeexifra/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Runner.build/Release-iphoneos/Runner.build/Script-9740EEB61CF901F6004384FC.sh
(1 failure)
```

When checking in the Runner target of the IOS project I can find the following script:
```
/bin/sh "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" build
```

I guess the error is coming from this script that fails.

I could not find any env variables set after the Flutter installer runs. Is there a way to get the Flutter installation folder so we can set the $FLUTTER_ROOT env variable require by this step.

**Comment by fehersanyi-bitrise** [comment]
Hello there, could you send me this build's url so I can check the full logs for some more details? 🙃

**Comment by AlexandreRoba** [comment]
Hi @fehersanyi-bitrise You guys are fast :)

Here is the link https://app.bitrise.io/build/0952422bdfc5c528

**Comment by fehersanyi-bitrise** [comment]
So I found a few threads on this exact issue
this would be the most prominent I guess https://stackoverflow.com/questions/52577639/flutter-ios-command-bin-sh-failed-with-exit-code-255

also if you can use xcode, https://github.com/flutter/flutter/issues/26338

oh yes, but first I would simply try to rebuild because the raw log said that `Compiler terminated unexpectedly.` so it may be some bug in the universe of random 🤔

**Comment by AlexandreRoba** [comment]
Ok weird... I tried couple of time already.. :(

Not mentionning that it builds and Archive on my laptop properly.

**Comment by fehersanyi-bitrise** [comment]
I understand your frustration, I will have to synch with the tooling team, they know the platform in and out. I'm sure they will be able to help you out

**Comment by lpusok** [comment]
Hi @AlexandreRoba,
Can you specify the clean build option for xcode-archive and disable bitcode?
Please check that you are using the same version of flutter and Xcode on your development machine as the build VM. Add the --verbose additional option for flutter-build. Add the flutter-analyze step before the xcode-archive step. Can also check the same workflow on a clean build state on the development machine.
